server:
  port: 8082
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development=true:
  shutdown: graceful

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${postgre.url}
    username: ${postgre.username}
    password: ${postgre.password}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_schema: soohofit
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org.hibernate:
        type.descriptor: trace
        sql: debug