server:
  port: 8080
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development=true:

spring:

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${postgre.url}
    username: ${postgre.username}
    password: ${postgre.password}

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true