server:
  port: 8080
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development=true:
    session:
      cookie:
        path: /
        http-only: true
        secure: true
      timeout: 3600
  #        domain: 도메인 나오면 추가
  shutdown: graceful


spring:

  jwt:
    secret: soohofitsoohofitsoohofitsoohofitsoohofitsoohofitsoohofitsoohofitsoohofitsoohofit

  session:
    redis:
      repository-type: default

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${postgre.url}
    username: ${postgre.username}
    password: ${postgre.password}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_schema: soohofit
        show_sql: true
        use_sql_comments: true
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 835705296716-n61ernocamco5o95f8plgdf7hp6oodua.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
#            client-id: 0ff01f0a268ff9f9adefd55604b125d7
            client-id: 56e60b9d77214ee307580394e29287b7
#            client-secret: bGMpDbPwFSfSozVo6LCIhuj6d29p40xv
            client-secret: B6yNzMq5JkDMAEtmPvVedTJAAhfDWlrp
            scope:
              - profile_nickname
              - account_email
#              - gender
#              - birthday
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            client-authentication-method: POST
            client-authentication-method: client_secret_post
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    org.hibernate:
      type.descriptor: trace
      sql: debug




