server:
  port: 8080
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development=true:

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://144.24.87.137:35432/soohofit?serverTimezone=Asia/Seoul
    username: soohofit
    password: soohofit1

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true